import Head from 'next/head'
import styled from 'styled-components';
import { Act } from '@/components/Act';
import { useActs } from '@/hooks/useActs';
import Link from 'next/link';

const ActList = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  padding: 6rem;
  min-height: 100vh;
`;

const BeetSheetHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

const BeetSheetActions = styled.div`
  display: flex;
  justify-content: flex-end;
`;

export default function BeetSheetPage() {

  // would add loading states and server side fetch
  // error handling
  const { data: acts } = useActs();

  return (
    <>
      <Head>
        <title>Beat Sheet Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BeetSheetHeader>
        <h1>My Video Beatsheet</h1>
        <BeetSheetActions>
          <Link href="/act/new">
            <button>New Act</button>
          </Link>
        </BeetSheetActions>
      </BeetSheetHeader>
      <ActList>
        <h1>Acts:</h1>
        {acts?.map(act => <Act act={act} key={act.id}/>)}
      </ActList>
    </>
  )
}
